FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY build/libs/insurance-rest-api-1.0.0.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]




FROM gradle:5.3.1-jdk8-alpine

ADD --chown=gradle:gradle . /home/gradle
WORKDIR /home/gradle

ENTRYPOINT ["gradle","run", "--stacktrace"]
