version: '3.7'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: insurance
    ports:
      - 5000:5432

  web:
    build: .
    depends_on:
      - db
    ports:
      - 8443:8443
